

# Request 예시들입니다. 

POST http://localhost:8000/ask
Content-Type: application/json 

{
    "user_id":"jinu123",
    "question":"수익성도?",
    "tab_name":"리포트버뷰",
    "company_name":"농심"
}

###
POST http://localhost:8000/ask
Content-Type: application/json

{
    "user_id":"byeongsin123",
    "question":"어흥!",
    "tab_name":"report_overview",
    "company_name":"lg에너지솔루션"
}


###
POST http://localhost:8000/prevqna/company
Content-Type: application/json

{
    "user_id":"byeongsin123",
    "question":"어흥!",
    "tab_name":"report_overview",
    "company_name":"lg에너지솔루션"
}

###
POST http://localhost:8000/prevqna/delete
Content-Type: application/json

{
    "user_id":"byeongsin123",
    "question":"어흥!",
    "tab_name":"리포트오버뷰",
    "company_name":"lg에너지솔루션"
}


###
GET http://localhost:8000/companies/097950/financial-analysis-details
Content-Type: application/json


###
GET http://localhost:8000/companies/097950/profile
Content-Type: application/json
