

# Request 예시들입니다. 

POST http://localhost:8000/ask
Content-Type: application/json 

{
    "user_id":"jinu123",
    "question":"안녕!",
    "tab_name":"report_overview",
    "company_name":"lg에너지솔루션"
}

###
POST http://localhost:8000/ask
Content-Type: application/json

{
    "user_id":"byeongsin123",
    "question":"어흥!",
    "tab_name":"report_overview",
    "company_name":"lg에너지솔루션"
}


###
POST http://localhost:8000/prevqna/company
Content-Type: application/json

{
    "user_id":"byeongsin123",
    "question":"어흥!",
    "tab_name":"report_overview",
    "company_name":"lg에너지솔루션"
}

###
POST http://localhost:8000/prevqna/delete
Content-Type: application/json

{
    "user_id":"byeongsin123",
    "question":"어흥!",
    "tab_name":"report_overview",
    "company_name":"lg에너지솔루션"
}